name: build kernel
on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: test
        run: |
          mkdir test
          touch test/st
          echo "${GITHUB_REF#refs/heads/}"

      - name: clone ak3
        run: |
          git clone https://github.com/CCCC-L/anyKernel3 releases
          sed -i "s/{branch}/${{ github.ref_name }}/" releases/anykernel.sh
          rm -rf releases/.git

      - name: Upload boot
        uses: actions/upload-artifact@v4
        with:
          name: boot-${{ github.ref_name }}
          path: releases
